// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	seckillOrderFieldNames          = builder.RawFieldNames(&SeckillOrder{})
	seckillOrderRows                = strings.Join(seckillOrderFieldNames, ",")
	seckillOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(seckillOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	seckillOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(seckillOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	seckillOrderModel interface {
		Insert(ctx context.Context, data *SeckillOrder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SeckillOrder, error)
		FindOneByOrderNo(ctx context.Context, orderNo string) (*SeckillOrder, error)
		Update(ctx context.Context, data *SeckillOrder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSeckillOrderModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SeckillOrder struct {
		Id         int64     `db:"id"`
		OrderNo    string    `db:"order_no"`
		UserId     int64     `db:"user_id"`
		ActId      int64     `db:"act_id"`
		Status     int64     `db:"status"`
		CreateTime time.Time `db:"create_time"`
	}
)

func newSeckillOrderModel(conn sqlx.SqlConn) *defaultSeckillOrderModel {
	return &defaultSeckillOrderModel{
		conn:  conn,
		table: "`seckill_order`",
	}
}

func (m *defaultSeckillOrderModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSeckillOrderModel) FindOne(ctx context.Context, id int64) (*SeckillOrder, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", seckillOrderRows, m.table)
	var resp SeckillOrder
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeckillOrderModel) FindOneByOrderNo(ctx context.Context, orderNo string) (*SeckillOrder, error) {
	var resp SeckillOrder
	query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", seckillOrderRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeckillOrderModel) Insert(ctx context.Context, data *SeckillOrder) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, seckillOrderRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.UserId, data.ActId, data.Status)
	return ret, err
}

func (m *defaultSeckillOrderModel) Update(ctx context.Context, newData *SeckillOrder) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, seckillOrderRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.OrderNo, newData.UserId, newData.ActId, newData.Status, newData.Id)
	return err
}

func (m *defaultSeckillOrderModel) tableName() string {
	return m.table
}
