// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateActReq struct {
	Name    string `json:"name"`
	Stock   int    `json:"stock"`
	StartAt int64  `json:"startAt"`
	EndAt   int64  `json:"endAt"`
}

type CreateActResp struct {
	ActivityId int64 `json:"activityId"`
}

type OrderStatusReq struct {
	OrderNo string `json:"orderNo" form:"orderNo"`
}

type OrderStatusResp struct {
	OrderNo string `json:"orderNo"`
	Status  int32  `json:"status"`
}

type SeckillReq struct {
	ActivityId int64 `json:"activityId"`
}

type SeckillResp struct {
	OrderNo string `json:"orderNo"`
	Message string `json:"message"`
}
