// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"seckill/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/act/create",
				Handler: CreateActHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/order/status",
				Handler: OrderStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/seckill",
				Handler: SeckillHandler(serverCtx),
			},
		},
	)
}
